language: python - "2.7"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:
    - conda install --yes python="2.7" sphinx
    - pip install sphinxcontrib-fulltoc

script:
     - sphinx-build -nW -b dirhtml -d _build/doctrees source _build/html

before_deploy:
  - mv ~/build/Cloudry/Website-sphinx/_build/html/* ~/build/Cloudry/Website-sphinx/
  - rm -rf ~/build/Cloudry/Website-sphinx/_build
  - rm -rf ~/build/Cloudry/Website-sphinx/_sources
#Cloudry/Website-sphinx
deploy:
  skip_cleanup: true
  provider: azure_web_apps
  edge:
    source: A92hm/dpl
    branch: master
  on:
    all_branches: true

sudo: false


notifications:
  slack: azured:PleVuyAMUhA8lOsGrQWAxVyi
